# Which Docker image shall be used on the GitLab runner?
image: registry.git.chalmers.se/courses/dit638/students/docker/docker:19.03.3

# Details about how to connect to the Docker service to run this build.
variables:
  DOCKER_HOST: tcp://docker:2375
  DOCKER_TLS_CERTDIR: ""

services:
  - name: registry.git.chalmers.se/courses/dit638/students/docker/docker:19.03.3-dind
    alias: docker

stages:
  - build
  - deploy

# Display information before we start the build.
before_script:
  - docker info
  - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY

# This section describes what shall be done to build and test the project.
build-and-test:
  tags:
    - docker-build
  stage: build
  script:
    - docker build -f Dockerfile .
  except:
    - tags

# This section describes what shall be done to deploy artefacts from the project.
release:
  tags:
    - docker-build
  stage: deploy
  script:
    # Install buildx
    - export DOCKER_CLI_EXPERIMENTAL=enabled
    - mkdir -p ~/.docker/cli-plugins
    - cd ~/.docker/cli-plugins/
    - wget https://github.com/docker/buildx/releases/download/v0.5.1/buildx-v0.5.1.linux-amd64
    - mv buildx-v0.5.1.linux-amd64 docker-buildx
    - chmod 755 docker-buildx
    - docker info
    - docker version
    # Build with buildx
    - cd /builds/courses/dit638/students/2021-group-08
    - docker buildx create --name platformbuilder --use
    - docker buildx inspect --bootstrap
    - docker buildx build --push --platform linux/amd64,linux/arm64,linux/arm/v7 -t "$CI_REGISTRY_IMAGE":"$CI_COMMIT_TAG" .
    # linux/arm/v6, for the reason please check back CI pipeline log
  when: on_success
  only:
    - tags
    - /^v[0-9]+(?:.[0-9]+)+[-0-9A-Za-z_]*$/